spring.application.name=LRE_Project

#main
spring.datasource.url=jdbc:postgresql://195.35.45.56:5432/local_real_estate_database
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=5858



# Max file size for single file
spring.servlet.multipart.max-file-size=200MB
# Max request size (total size for all files in a request)
spring.servlet.multipart.max-request-size=250MB
